### ISSUE TITLE
我们直接把你拉进组织

### ISSUE THREAD

**Issue by lizzy-0323** [ichont/DMU-Course-Help#1]
我们也毕业一年了，把你直接拉进组织，直接参与仓库的管理吧，这样也不浪费老项目的star

**Comment by ichont** [comment]
拉我吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ichont/DMU-Course-Help"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月13日(星期四) 下午2:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ichont/DMU-Course-Help] 我们直接把你拉进组织 (Issue #1)





 
我们也毕业一年了，把你直接拉进组织，直接参与仓库的管理吧，这样也不浪费老项目的star

**Comment by lizzy-0323** [comment]
> 拉我吧
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ichont/DMU-Course-Help" ***@***.***&gt;; 发送时间:&nbsp;2024年6月13日(星期四) 下午2:29 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[ichont/DMU-Course-Help] 我们直接把你拉进组织 (Issue #1) 我们也毕业一年了，把你直接拉进组织，直接参与仓库的管理吧，这样也不浪费老项目的star — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

已拉，目前主要需要你完善一下相关文档，提供简单的教程，另外想问一下你现在的年级？

**Comment by ichont** [comment]
22级智科，平时没什么时间，暑期再完善readme吧



---原始邮件---
发件人: "Ziyi ***@***.***&gt;
发送时间: 2024年6月13日(周四) 下午2:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ichont/DMU-Course-Help] 我们直接把你拉进组织 (Issue #1)




  
拉我吧
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ichont/DMU-Course-Help" @.&gt;; 发送时间:&nbsp;2024年6月13日(星期四) 下午2:29 @.&gt;; @.&gt;; 主题:&nbsp;[ichont/DMU-Course-Help] 我们直接把你拉进组织 (Issue #1) 我们也毕业一年了，把你直接拉进组织，直接参与仓库的管理吧，这样也不浪费老项目的star — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
已拉，目前主要需要你完善一下相关文档，提供简单的教程，另外想问一下你现在的年级？

**Comment by AkimioJR** [comment]
> 我们也毕业一年了，把你直接拉进组织，直接参与仓库的管理吧，这样也不浪费老项目的star

学长，看您项目go用的比较多，现在是去了武汉大学深造吗
